package net.opentrends.register.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Address service. Represents a row in the &quot;StudentPortlet_Address&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link net.opentrends.register.model.impl.AddressModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link net.opentrends.register.model.impl.AddressImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Address
 * @see net.opentrends.register.model.impl.AddressImpl
 * @see net.opentrends.register.model.impl.AddressModelImpl
 * @generated
 */
public interface AddressModel extends BaseModel<Address> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a address model instance should use the {@link Address} interface instead.
     */

    /**
     * Returns the primary key of this address.
     *
     * @return the primary key of this address
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this address.
     *
     * @param primaryKey the primary key of this address
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the address ID of this address.
     *
     * @return the address ID of this address
     */
    public long getAddressId();

    /**
     * Sets the address ID of this address.
     *
     * @param addressId the address ID of this address
     */
    public void setAddressId(long addressId);

    /**
     * Returns the student ID of this address.
     *
     * @return the student ID of this address
     */
    public long getStudentId();

    /**
     * Sets the student ID of this address.
     *
     * @param studentId the student ID of this address
     */
    public void setStudentId(long studentId);

    /**
     * Returns the group ID of this address.
     *
     * @return the group ID of this address
     */
    public long getGroupId();

    /**
     * Sets the group ID of this address.
     *
     * @param groupId the group ID of this address
     */
    public void setGroupId(long groupId);

    /**
     * Returns the parent address of this address.
     *
     * @return the parent address of this address
     */
    @AutoEscape
    public String getParentAddress();

    /**
     * Sets the parent address of this address.
     *
     * @param parentAddress the parent address of this address
     */
    public void setParentAddress(String parentAddress);

    /**
     * Returns the parent state of this address.
     *
     * @return the parent state of this address
     */
    @AutoEscape
    public String getParentState();

    /**
     * Sets the parent state of this address.
     *
     * @param parentState the parent state of this address
     */
    public void setParentState(String parentState);

    /**
     * Returns the parent district of this address.
     *
     * @return the parent district of this address
     */
    @AutoEscape
    public String getParentDistrict();

    /**
     * Sets the parent district of this address.
     *
     * @param parentDistrict the parent district of this address
     */
    public void setParentDistrict(String parentDistrict);

    /**
     * Returns the parent pin of this address.
     *
     * @return the parent pin of this address
     */
    @AutoEscape
    public String getParentPin();

    /**
     * Sets the parent pin of this address.
     *
     * @param parentPin the parent pin of this address
     */
    public void setParentPin(String parentPin);

    /**
     * Returns the parent phone of this address.
     *
     * @return the parent phone of this address
     */
    @AutoEscape
    public String getParentPhone();

    /**
     * Sets the parent phone of this address.
     *
     * @param parentPhone the parent phone of this address
     */
    public void setParentPhone(String parentPhone);

    /**
     * Returns the parent mail of this address.
     *
     * @return the parent mail of this address
     */
    @AutoEscape
    public String getParentMail();

    /**
     * Sets the parent mail of this address.
     *
     * @param parentMail the parent mail of this address
     */
    public void setParentMail(String parentMail);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(net.opentrends.register.model.Address address);

    @Override
    public int hashCode();

    @Override
    public CacheModel<net.opentrends.register.model.Address> toCacheModel();

    @Override
    public net.opentrends.register.model.Address toEscapedModel();

    @Override
    public net.opentrends.register.model.Address toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
