package net.opentrends.register.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Student service. Represents a row in the &quot;StudentPortlet_Student&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link net.opentrends.register.model.impl.StudentModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link net.opentrends.register.model.impl.StudentImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Student
 * @see net.opentrends.register.model.impl.StudentImpl
 * @see net.opentrends.register.model.impl.StudentModelImpl
 * @generated
 */
public interface StudentModel extends BaseModel<Student> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a student model instance should use the {@link Student} interface instead.
     */

    /**
     * Returns the primary key of this student.
     *
     * @return the primary key of this student
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this student.
     *
     * @param primaryKey the primary key of this student
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the student ID of this student.
     *
     * @return the student ID of this student
     */
    public long getStudentId();

    /**
     * Sets the student ID of this student.
     *
     * @param studentId the student ID of this student
     */
    public void setStudentId(long studentId);

    /**
     * Returns the group ID of this student.
     *
     * @return the group ID of this student
     */
    public long getGroupId();

    /**
     * Sets the group ID of this student.
     *
     * @param groupId the group ID of this student
     */
    public void setGroupId(long groupId);

    /**
     * Returns the student name of this student.
     *
     * @return the student name of this student
     */
    @AutoEscape
    public String getStudentName();

    /**
     * Sets the student name of this student.
     *
     * @param studentName the student name of this student
     */
    public void setStudentName(String studentName);

    /**
     * Returns the student class of this student.
     *
     * @return the student class of this student
     */
    @AutoEscape
    public String getStudentClass();

    /**
     * Sets the student class of this student.
     *
     * @param studentClass the student class of this student
     */
    public void setStudentClass(String studentClass);

    /**
     * Returns the student email of this student.
     *
     * @return the student email of this student
     */
    @AutoEscape
    public String getStudentEmail();

    /**
     * Sets the student email of this student.
     *
     * @param studentEmail the student email of this student
     */
    public void setStudentEmail(String studentEmail);

    /**
     * Returns the phone number of this student.
     *
     * @return the phone number of this student
     */
    @AutoEscape
    public String getPhoneNumber();

    /**
     * Sets the phone number of this student.
     *
     * @param phoneNumber the phone number of this student
     */
    public void setPhoneNumber(String phoneNumber);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(net.opentrends.register.model.Student student);

    @Override
    public int hashCode();

    @Override
    public CacheModel<net.opentrends.register.model.Student> toCacheModel();

    @Override
    public net.opentrends.register.model.Student toEscapedModel();

    @Override
    public net.opentrends.register.model.Student toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
