package net.opentrends.training.service.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Employee_portlet service. Represents a row in the &quot;TestPortlet_Employee_portlet&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link net.opentrends.training.service.model.impl.Employee_portletModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link net.opentrends.training.service.model.impl.Employee_portletImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Employee_portlet
 * @see net.opentrends.training.service.model.impl.Employee_portletImpl
 * @see net.opentrends.training.service.model.impl.Employee_portletModelImpl
 * @generated
 */
public interface Employee_portletModel extends BaseModel<Employee_portlet> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a employee_portlet model instance should use the {@link Employee_portlet} interface instead.
     */

    /**
     * Returns the primary key of this employee_portlet.
     *
     * @return the primary key of this employee_portlet
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this employee_portlet.
     *
     * @param primaryKey the primary key of this employee_portlet
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the employee ID of this employee_portlet.
     *
     * @return the employee ID of this employee_portlet
     */
    public long getEmployeeId();

    /**
     * Sets the employee ID of this employee_portlet.
     *
     * @param employeeId the employee ID of this employee_portlet
     */
    public void setEmployeeId(long employeeId);

    /**
     * Returns the group ID of this employee_portlet.
     *
     * @return the group ID of this employee_portlet
     */
    public long getGroupId();

    /**
     * Sets the group ID of this employee_portlet.
     *
     * @param groupId the group ID of this employee_portlet
     */
    public void setGroupId(long groupId);

    /**
     * Returns the company ID of this employee_portlet.
     *
     * @return the company ID of this employee_portlet
     */
    public long getCompanyId();

    /**
     * Sets the company ID of this employee_portlet.
     *
     * @param companyId the company ID of this employee_portlet
     */
    public void setCompanyId(long companyId);

    /**
     * Returns the user ID of this employee_portlet.
     *
     * @return the user ID of this employee_portlet
     */
    public long getUserId();

    /**
     * Sets the user ID of this employee_portlet.
     *
     * @param userId the user ID of this employee_portlet
     */
    public void setUserId(long userId);

    /**
     * Returns the user uuid of this employee_portlet.
     *
     * @return the user uuid of this employee_portlet
     * @throws SystemException if a system exception occurred
     */
    public String getUserUuid() throws SystemException;

    /**
     * Sets the user uuid of this employee_portlet.
     *
     * @param userUuid the user uuid of this employee_portlet
     */
    public void setUserUuid(String userUuid);

    /**
     * Returns the user name of this employee_portlet.
     *
     * @return the user name of this employee_portlet
     */
    @AutoEscape
    public String getUserName();

    /**
     * Sets the user name of this employee_portlet.
     *
     * @param userName the user name of this employee_portlet
     */
    public void setUserName(String userName);

    /**
     * Returns the address of this employee_portlet.
     *
     * @return the address of this employee_portlet
     */
    @AutoEscape
    public String getAddress();

    /**
     * Sets the address of this employee_portlet.
     *
     * @param address the address of this employee_portlet
     */
    public void setAddress(String address);

    /**
     * Returns the email of this employee_portlet.
     *
     * @return the email of this employee_portlet
     */
    @AutoEscape
    public String getEmail();

    /**
     * Sets the email of this employee_portlet.
     *
     * @param email the email of this employee_portlet
     */
    public void setEmail(String email);

    /**
     * Returns the phone number of this employee_portlet.
     *
     * @return the phone number of this employee_portlet
     */
    @AutoEscape
    public String getPhoneNumber();

    /**
     * Sets the phone number of this employee_portlet.
     *
     * @param phoneNumber the phone number of this employee_portlet
     */
    public void setPhoneNumber(String phoneNumber);

    /**
     * Returns the password of this employee_portlet.
     *
     * @return the password of this employee_portlet
     */
    @AutoEscape
    public String getPassword();

    /**
     * Sets the password of this employee_portlet.
     *
     * @param password the password of this employee_portlet
     */
    public void setPassword(String password);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(
        net.opentrends.training.service.model.Employee_portlet employee_portlet);

    @Override
    public int hashCode();

    @Override
    public CacheModel<net.opentrends.training.service.model.Employee_portlet> toCacheModel();

    @Override
    public net.opentrends.training.service.model.Employee_portlet toEscapedModel();

    @Override
    public net.opentrends.training.service.model.Employee_portlet toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
