package net.opentrends.register.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import net.opentrends.register.model.Address;
import net.opentrends.register.service.AddressLocalServiceUtil;

/**
 * The extended model base implementation for the Address service. Represents a row in the &quot;StudentPortlet_Address&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AddressImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AddressImpl
 * @see net.opentrends.register.model.Address
 * @generated
 */
public abstract class AddressBaseImpl extends AddressModelImpl
    implements Address {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a address model instance should use the {@link Address} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            AddressLocalServiceUtil.addAddress(this);
        } else {
            AddressLocalServiceUtil.updateAddress(this);
        }
    }
}
