package net.opentrends.register.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import net.opentrends.register.model.Student;
import net.opentrends.register.model.StudentModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the Student service. Represents a row in the &quot;StudentPortlet_Student&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link net.opentrends.register.model.StudentModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link StudentImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see StudentImpl
 * @see net.opentrends.register.model.Student
 * @see net.opentrends.register.model.StudentModel
 * @generated
 */
public class StudentModelImpl extends BaseModelImpl<Student>
    implements StudentModel {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a student model instance should use the {@link net.opentrends.register.model.Student} interface instead.
     */
    public static final String TABLE_NAME = "StudentPortlet_Student";
    public static final Object[][] TABLE_COLUMNS = {
            { "studentId", Types.BIGINT },
            { "groupId", Types.BIGINT },
            { "studentName", Types.VARCHAR },
            { "studentClass", Types.VARCHAR },
            { "studentEmail", Types.VARCHAR },
            { "phoneNumber", Types.VARCHAR }
        };
    public static final String TABLE_SQL_CREATE = "create table StudentPortlet_Student (studentId LONG not null primary key,groupId LONG,studentName VARCHAR(75) null,studentClass VARCHAR(75) null,studentEmail VARCHAR(75) null,phoneNumber VARCHAR(75) null)";
    public static final String TABLE_SQL_DROP = "drop table StudentPortlet_Student";
    public static final String ORDER_BY_JPQL = " ORDER BY student.studentId ASC";
    public static final String ORDER_BY_SQL = " ORDER BY StudentPortlet_Student.studentId ASC";
    public static final String DATA_SOURCE = "liferayDataSource";
    public static final String SESSION_FACTORY = "liferaySessionFactory";
    public static final String TX_MANAGER = "liferayTransactionManager";
    public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.entity.cache.enabled.net.opentrends.register.model.Student"),
            true);
    public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.finder.cache.enabled.net.opentrends.register.model.Student"),
            true);
    public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.column.bitmask.enabled.net.opentrends.register.model.Student"),
            true);
    public static long GROUPID_COLUMN_BITMASK = 1L;
    public static long STUDENTID_COLUMN_BITMASK = 2L;
    public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
                "lock.expiration.time.net.opentrends.register.model.Student"));
    private static ClassLoader _classLoader = Student.class.getClassLoader();
    private static Class<?>[] _escapedModelInterfaces = new Class[] {
            Student.class
        };
    private long _studentId;
    private long _groupId;
    private long _originalGroupId;
    private boolean _setOriginalGroupId;
    private String _studentName;
    private String _studentClass;
    private String _studentEmail;
    private String _phoneNumber;
    private long _columnBitmask;
    private Student _escapedModel;

    public StudentModelImpl() {
    }

    @Override
    public long getPrimaryKey() {
        return _studentId;
    }

    @Override
    public void setPrimaryKey(long primaryKey) {
        setStudentId(primaryKey);
    }

    @Override
    public Serializable getPrimaryKeyObj() {
        return _studentId;
    }

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj) {
        setPrimaryKey(((Long) primaryKeyObj).longValue());
    }

    @Override
    public Class<?> getModelClass() {
        return Student.class;
    }

    @Override
    public String getModelClassName() {
        return Student.class.getName();
    }

    @Override
    public Map<String, Object> getModelAttributes() {
        Map<String, Object> attributes = new HashMap<String, Object>();

        attributes.put("studentId", getStudentId());
        attributes.put("groupId", getGroupId());
        attributes.put("studentName", getStudentName());
        attributes.put("studentClass", getStudentClass());
        attributes.put("studentEmail", getStudentEmail());
        attributes.put("phoneNumber", getPhoneNumber());

        return attributes;
    }

    @Override
    public void setModelAttributes(Map<String, Object> attributes) {
        Long studentId = (Long) attributes.get("studentId");

        if (studentId != null) {
            setStudentId(studentId);
        }

        Long groupId = (Long) attributes.get("groupId");

        if (groupId != null) {
            setGroupId(groupId);
        }

        String studentName = (String) attributes.get("studentName");

        if (studentName != null) {
            setStudentName(studentName);
        }

        String studentClass = (String) attributes.get("studentClass");

        if (studentClass != null) {
            setStudentClass(studentClass);
        }

        String studentEmail = (String) attributes.get("studentEmail");

        if (studentEmail != null) {
            setStudentEmail(studentEmail);
        }

        String phoneNumber = (String) attributes.get("phoneNumber");

        if (phoneNumber != null) {
            setPhoneNumber(phoneNumber);
        }
    }

    @Override
    public long getStudentId() {
        return _studentId;
    }

    @Override
    public void setStudentId(long studentId) {
        _studentId = studentId;
    }

    @Override
    public long getGroupId() {
        return _groupId;
    }

    @Override
    public void setGroupId(long groupId) {
        _columnBitmask |= GROUPID_COLUMN_BITMASK;

        if (!_setOriginalGroupId) {
            _setOriginalGroupId = true;

            _originalGroupId = _groupId;
        }

        _groupId = groupId;
    }

    public long getOriginalGroupId() {
        return _originalGroupId;
    }

    @Override
    public String getStudentName() {
        if (_studentName == null) {
            return StringPool.BLANK;
        } else {
            return _studentName;
        }
    }

    @Override
    public void setStudentName(String studentName) {
        _studentName = studentName;
    }

    @Override
    public String getStudentClass() {
        if (_studentClass == null) {
            return StringPool.BLANK;
        } else {
            return _studentClass;
        }
    }

    @Override
    public void setStudentClass(String studentClass) {
        _studentClass = studentClass;
    }

    @Override
    public String getStudentEmail() {
        if (_studentEmail == null) {
            return StringPool.BLANK;
        } else {
            return _studentEmail;
        }
    }

    @Override
    public void setStudentEmail(String studentEmail) {
        _studentEmail = studentEmail;
    }

    @Override
    public String getPhoneNumber() {
        if (_phoneNumber == null) {
            return StringPool.BLANK;
        } else {
            return _phoneNumber;
        }
    }

    @Override
    public void setPhoneNumber(String phoneNumber) {
        _phoneNumber = phoneNumber;
    }

    public long getColumnBitmask() {
        return _columnBitmask;
    }

    @Override
    public ExpandoBridge getExpandoBridge() {
        return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
            Student.class.getName(), getPrimaryKey());
    }

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
        ExpandoBridge expandoBridge = getExpandoBridge();

        expandoBridge.setAttributes(serviceContext);
    }

    @Override
    public Student toEscapedModel() {
        if (_escapedModel == null) {
            _escapedModel = (Student) ProxyUtil.newProxyInstance(_classLoader,
                    _escapedModelInterfaces, new AutoEscapeBeanHandler(this));
        }

        return _escapedModel;
    }

    @Override
    public Object clone() {
        StudentImpl studentImpl = new StudentImpl();

        studentImpl.setStudentId(getStudentId());
        studentImpl.setGroupId(getGroupId());
        studentImpl.setStudentName(getStudentName());
        studentImpl.setStudentClass(getStudentClass());
        studentImpl.setStudentEmail(getStudentEmail());
        studentImpl.setPhoneNumber(getPhoneNumber());

        studentImpl.resetOriginalValues();

        return studentImpl;
    }

    @Override
    public int compareTo(Student student) {
        long primaryKey = student.getPrimaryKey();

        if (getPrimaryKey() < primaryKey) {
            return -1;
        } else if (getPrimaryKey() > primaryKey) {
            return 1;
        } else {
            return 0;
        }
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }

        if (!(obj instanceof Student)) {
            return false;
        }

        Student student = (Student) obj;

        long primaryKey = student.getPrimaryKey();

        if (getPrimaryKey() == primaryKey) {
            return true;
        } else {
            return false;
        }
    }

    @Override
    public int hashCode() {
        return (int) getPrimaryKey();
    }

    @Override
    public void resetOriginalValues() {
        StudentModelImpl studentModelImpl = this;

        studentModelImpl._originalGroupId = studentModelImpl._groupId;

        studentModelImpl._setOriginalGroupId = false;

        studentModelImpl._columnBitmask = 0;
    }

    @Override
    public CacheModel<Student> toCacheModel() {
        StudentCacheModel studentCacheModel = new StudentCacheModel();

        studentCacheModel.studentId = getStudentId();

        studentCacheModel.groupId = getGroupId();

        studentCacheModel.studentName = getStudentName();

        String studentName = studentCacheModel.studentName;

        if ((studentName != null) && (studentName.length() == 0)) {
            studentCacheModel.studentName = null;
        }

        studentCacheModel.studentClass = getStudentClass();

        String studentClass = studentCacheModel.studentClass;

        if ((studentClass != null) && (studentClass.length() == 0)) {
            studentCacheModel.studentClass = null;
        }

        studentCacheModel.studentEmail = getStudentEmail();

        String studentEmail = studentCacheModel.studentEmail;

        if ((studentEmail != null) && (studentEmail.length() == 0)) {
            studentCacheModel.studentEmail = null;
        }

        studentCacheModel.phoneNumber = getPhoneNumber();

        String phoneNumber = studentCacheModel.phoneNumber;

        if ((phoneNumber != null) && (phoneNumber.length() == 0)) {
            studentCacheModel.phoneNumber = null;
        }

        return studentCacheModel;
    }

    @Override
    public String toString() {
        StringBundler sb = new StringBundler(13);

        sb.append("{studentId=");
        sb.append(getStudentId());
        sb.append(", groupId=");
        sb.append(getGroupId());
        sb.append(", studentName=");
        sb.append(getStudentName());
        sb.append(", studentClass=");
        sb.append(getStudentClass());
        sb.append(", studentEmail=");
        sb.append(getStudentEmail());
        sb.append(", phoneNumber=");
        sb.append(getPhoneNumber());
        sb.append("}");

        return sb.toString();
    }

    @Override
    public String toXmlString() {
        StringBundler sb = new StringBundler(22);

        sb.append("<model><model-name>");
        sb.append("net.opentrends.register.model.Student");
        sb.append("</model-name>");

        sb.append(
            "<column><column-name>studentId</column-name><column-value><![CDATA[");
        sb.append(getStudentId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>groupId</column-name><column-value><![CDATA[");
        sb.append(getGroupId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>studentName</column-name><column-value><![CDATA[");
        sb.append(getStudentName());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>studentClass</column-name><column-value><![CDATA[");
        sb.append(getStudentClass());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>studentEmail</column-name><column-value><![CDATA[");
        sb.append(getStudentEmail());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>phoneNumber</column-name><column-value><![CDATA[");
        sb.append(getPhoneNumber());
        sb.append("]]></column-value></column>");

        sb.append("</model>");

        return sb.toString();
    }
}
